(load advising.clp)
(load "rules_Bachelor of Computer Science (General).clp")
(reset)
(assert (cur-term (term f)))
(assert (has-taken (course 62-120))) 
(assert (has-taken (course 62-125))) 
(assert (has-taken (course 62-130))) 
(assert (courseCompleted n)))
(run)
(close)
(exit)
(exit)
