(load advising.clp)
(load "rules_Title of Program.clp")
(reset)
(assert (cur-term (term f)))
(assert (has-taken (course 62-125))) 
(assert (has-taken (course 62-130))) 
(assert (has-taken (course 62-139))) 
(assert (has-taken (course 60-140))) 
(assert (courseCompleted n)))
(run)
(close)
(exit)
(exit)
